[package]
name = "test-efd-pp-syn"
version = "0.1.0"
edition = "2021"

[dependencies]
four-bar = { path = "../four-bar-rs/four-bar", features = ["plot"] }
indicatif = { version = "0.17", features = ["improved_unicode"] }
